### ISSUE TITLE
Dependency Injection 

### ISSUE THREAD

**Issue by stefan-uhlemann** [williamjuan027/nativescript-rootlayout-demo#5]
Hi,

great project, but i have problems with one feature in this demo.
It seems, the dependency injection for the input character is not working.
If i run "View Reorder" the Card i tap is always undefined (CardComponent, Input).

Running on Android 10

Thank you

**Comment by codephobia** [comment]
I am also running into this issue. Seems the input in getView for the UI Service was never handled.

```ts
getView(component, input?: any): Promise<View> {
  return new Promise((resolve) => {
    const cmpRef = generateNativeScriptView(component, {
      injector: this.injector
    });
    (<any>cmpRef.firstNativeLikeView).__ngRef = cmpRef.ref;
    resolve(cmpRef.firstNativeLikeView);
  });
}
```
