### ISSUE TITLE
Need to update cd command to get into demo app directory

### ISSUE THREAD

**Issue by brianrclow** [williamjuan027/nativescript-rootlayout-demo#7]
Hello,

In the readme you listed the command `cd nativescript-rootlayout-demo/ng-demo` to get into the demo app but the correct command should be `cd nativescript-rootlayout-demo/demo-ng` as "demo-ng" is the correct file path. Small change, I thought creating an issue would be quicker for you compared to forking and creating a PR for 2 word change. 

Thanks so much for this cool demo!

**Comment by williamjuan027** [comment]
Thanks @brianrclow :)

Updated the README in https://github.com/williamjuan027/nativescript-rootlayout-demo/commit/5535edc9fbcdad91014ba70ca68d7803eab3b704
