### ISSUE TITLE
npm ERR! missing script: start.android

### ISSUE THREAD

**Issue by cichy380** [williamjuan027/nativescript-rootlayout-demo#8]
I did everything according to the instructions (clone repo, install dependences), but when I used to command `npm run start.android` I got error:
```
npm ERR! missing script: start.android
```

PS
I started your demo by `ns run android`, but how should work `npm run start.android`  ?

**Comment by williamjuan027** [comment]
Thanks for pointing that out, seems like the scripts got deleted when we did an Angular 12 update (https://github.com/williamjuan027/nativescript-rootlayout-demo/commit/c0260b5b7e7cfe5f4eafa0e0fe3802edc5429560#diff-77f49514b7e05ae7431e9f925732ec150ba4e5615003ff9c0f0de00a33b26a25)

These were the scripts if you were curious :)

```javascript
"start.ios": "ns run ios --no-hmr",
"start.android": "ns run android --no-hmr",
```

I've updated the [README](https://github.com/williamjuan027/nativescript-rootlayout-demo/blob/master/README.md) to use the CLI commands directly.
